### ISSUE TITLE
Capturing blockhashes

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1009]
Blockhashes aren't being captured by replays. There are thus 2 issues here:

1. their capture and inclusion in the replay test json file
2. getting the replay tests to feed these blockhashes to the EVM testing environment

This issue is connected to https://github.com/Consensys/linea-tracer/issues/996.

**Comment by letypequividelespoubelles** [comment]
duplicate of #935
