### ISSUE TITLE
ToyWorld bug

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1044]
The test
```java
  @Test
  void issue1004() {
    replay("6020023-6020029.json.gz", false);
  }
```
Seems to run into a ToyWorld bug as per @DavePearce 

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/cd3dacf4-667b-4b06-a9f1-49c699dff699">

**Comment by DavePearce** [comment]
Resolved as part of #1027 / #1045
