### ISSUE TITLE
Why do we defer transactions in the HUB ?

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1050]
what's the purpose of this ?

_Originally posted by @letypequividelespoubelles in https://github.com/Consensys/linea-tracer/pull/1027#discussion_r1738487500_

**Comment by OlivierBBB** [comment]
So far the answer is: I don't remember 😅

**Comment by letypequividelespoubelles** [comment]
It seems that we don't resolve it.

And in any case, if needed, it would make more sense to just use the besu hook traceEndTx instead of differs ...
