### ISSUE TITLE
Run **all** the ranges nightly

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1101]
I have tagged all range related issues using the ranges label. We should have the nightly run execute them on on `arith-dev`, say. Ideally we could tag test in Java to be `@Nightly` so that we could run them on a nightly fashion, regardless of whether they are `@Disabled` or not.

**Note.** We have plenty of historical ranges that we aren't testing anymore, see issues in https://github.com/Consensys/linea-tracer/issues?q=label%3Aranges

**Comment by letypequividelespoubelles** [comment]
cf #1085
