### ISSUE TITLE
Duplicate of #1061

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1109]
Duplicate of #1061

## Ranges

```rust
6690-6699
```

## Issue

See #1061

**Comment by letypequividelespoubelles** [comment]
what's the point of creating a duplicate of the issue ?

**Comment by letypequividelespoubelles** [comment]
test is passing wo any modif : 
![image](https://github.com/user-attachments/assets/6a28e03c-c169-4dc5-8bc2-85cacf39ca86)
