### ISSUE TITLE
v0.5.3-beta constraints errors

### ISSUE THREAD

**Issue by gusiri** [Consensys/besu-sequencer-plugins#1111]
## Ranges

```rust
3108622-3108633
3175608-3175636
3290673-3290679
3290746-3290752
3315684-3315690
3374278-3374284
3385404-3385411
3410170-3410240
3423488-3423521
3424829-3424864
3429701-3429735
3431193-3431232
3431567-3431601
3432730-3432768
4323962-4324012
4343434-4343473
4392225-4392280
4477086-4477226
4519246-4519309
4556007-4556115
4583379-4583463
```

## Issue

Most of the `mmu` constraints errors reported in `v0.5.1-beta` have been resolved in `v0.5.3-beta`
There are still some `mmu` constraints errors. I can see `stp`, `exp` and  `oob`  as well. 

Link to the error logs: https://drive.google.com/drive/folders/1gJCR0VsXtwO666WUFlWTz8-XZv4a953J?usp=drive_link

**Investigation.**
- `mmu` $\Longrightarrow$ @letypequividelespoubelles 
- `stp` $\Longrightarrow$ @OlivierBBB 
- `exp` and `oob` $\Longrightarrow$ @lorenzogentile404

Example ranges
- [x] #1125
- [x] #1124
- [ ] `3108622-3108633` [mmu issue](https://github.com/Consensys/linea-tracer/issues/1121)
- [x] #1126

**Comment by letypequividelespoubelles** [comment]
Only #1121 is a real issue
