### ISSUE TITLE
OOB issue

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1126]
## Ranges

```rust
3108622-3108633
3175608-3175636
3290673-3290679
3290746-3290752
3315684-3315690
3374278-3374284
3385404-3385411
3410170-3410240
3423488-3423521
3424829-3424864
3429701-3429735
3431193-3431232
3431567-3431601
3432730-3432768
4323962-4324012
4343434-4343473
4392225-4392280
4477086-4477226
4519246-4519309
4556007-4556115
4583379-4583463
```

AFAICT the OOB constraints that are broken according to the log file are
```rust
oob.prc-modexp-pricing---div-big-numerator-by-quaddivisor#3
oob.prc-modexp-pricing---div-big-numerator-by-quaddivisor#4
oob.prc-modexp-pricing---div-max-xbs-ybs-square-plus-7-by-8#3
```

**Comment by letypequividelespoubelles** [comment]
same block as #1121 , so maybe common issue

**Comment by OlivierBBB** [comment]
Successes on my machine

- [ ] 3108622-3108633 $\color{red}{\mathtt{mmu.modexp-mmio-instruction-writting}}$
- [ ] 3175608-3175636 $\color{red}{\mathtt{mmu.modexp-mmio-instruction-writting}}$
- [x] 3290673-3290679
- [x] 3290746-3290752
- [x] 3315684-3315690
- [x] 3374278-3374284
- [x] 3385404-3385411
- [x] 3410170-3410240
- [x] 3423488-3423521
- [x] 3424829-3424864
- [x] 3429701-3429735
- [x] 3431193-3431232
- [x] 3431567-3431601
- [ ] 3432730-3432768 $\color{red}{\mathtt{mmu.modexp-mmio-instruction-writting}}$
- [x] 4323962-4324012
- [x] 4343434-4343473
- [ ] 4392225-4392280 $\color{red}{\mathtt{mmu.modexp-mmio-instruction-writting}}$
- [ ] 4477086-4477226 $\color{red}{\mathtt{mmu.modexp-mmio-instruction-writting}}$
- [x] 4519246-4519309
- [x] 4556007-4556115
- [x] 4583379-4583463

**Comment by OlivierBBB** [comment]
All of these 5 ranges that fail fail because of some sort of "off by 1" error.

<img width="1658" alt="image" src="https://github.com/user-attachments/assets/00fd2a36-2857-43bf-84c9-f69ddff570d4">

**Comment by letypequividelespoubelles** [comment]
MMU constraints issue #1121
