### ISSUE TITLE
Mark all the replay tests as `@Tag{"Nightly"}`

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1135]

**Comment by letypequividelespoubelles** [comment]
I'm clearly not in favor of this. We should tag all the replay duplicate file (the one coming from issue with a `range` label as a Nightly, but not ALL replay , to be sure to not introduce bugs. Of course, once we "copy" the behavior in an unit test that created the issue, we could mark it as `Nightly` /  discard it.
