### ISSUE TITLE
tracer for line count has issue with precompiles

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1141]
two servers give different counts:
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"v0.5.3-beta","blockNumber":353,"tracesCounters":{"EXT":7,"ADD":1,"LOG_INFO":13,"MXP":3,"TXN_DATA":73,"WCP":163,"ROM_LEX":1,"PRECOMPILE_BLAKE_ROUNDS":298,"BLOCK_TRANSACTIONS":8,"BLOCK_L1_SIZE":400,"LOG_DATA":1,"TRM":135,"PRECOMPILE_ECPAIRING_MILLER_LOOPS":298,"SHF":15,"EUC":5,"PRECOMPILE_SHA2_BLOCKS":298,"HUB":44,"EC_DATA":11,"PRECOMPILE_BLAKE_EFFECTIVE_CALLS":298,"PRECOMPILE_ECADD_EFFECTIVE_CALLS":298,"PRECOMPILE_MODEXP_EFFECTIVE_CALLS":298,"MMIO":0,"RLP_TXN":1008,"BLOCK_KECCAK":603,"MOD":7,"OOB":5,"MUL":9,"PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS":298,"PRECOMPILE_RIPEMD_BLOCKS":298,"BIN":15,"BLOCK_DATA":13,"RLP_ADDR":7,"PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS":298,"ROM":1,"PRECOMPILE_ECMUL_EFFECTIVE_CALLS":298,"MMU":10,"RLP_TXN_RCPT":679,"BLOCK_HASH":1,"EXP":5,"PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS":298}}}

or

{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"v0.5.3-beta","blockNumber":353,"tracesCounters":{"EXT":7,"ADD":1,"LOG_INFO":13,"MXP":3,"TXN_DATA":73,"WCP":163,"ROM_LEX":1,"PRECOMPILE_BLAKE_ROUNDS":83851713,"BLOCK_TRANSACTIONS":8,"BLOCK_L1_SIZE":400,"LOG_DATA":1,"TRM":135,"PRECOMPILE_ECPAIRING_MILLER_LOOPS":83851713,"SHF":15,"EUC":5,"PRECOMPILE_SHA2_BLOCKS":83851713,"HUB":44,"EC_DATA":11,"PRECOMPILE_BLAKE_EFFECTIVE_CALLS":83851713,"PRECOMPILE_ECADD_EFFECTIVE_CALLS":83851713,"PRECOMPILE_MODEXP_EFFECTIVE_CALLS":83851713,"MMIO":0,"RLP_TXN":1008,"BLOCK_KECCAK":167703433,"MOD":7,"OOB":5,"MUL":9,"PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS":83851713,"PRECOMPILE_RIPEMD_BLOCKS":83851713,"BIN":15,"BLOCK_DATA":13,"RLP_ADDR":7,"PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS":83851713,"ROM":1,"PRECOMPILE_ECMUL_EFFECTIVE_CALLS":83851713,"MMU":10,"RLP_TXN_RCPT":679,"BLOCK_HASH":1,"EXP":5,"PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS":83851713}}}

**Comment by FlorianHuc** [comment]
same for BLOCK_KECCAK":167703433

{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"v0.5.3-beta","blockNumber":6975,"tracesCounters":{"EXT":7,"ADD":1,"LOG_INFO":6,"MXP":3,"TXN_DATA":17,"WCP":45,"ROM_LEX":1,"PRECOMPILE_BLAKE_ROUNDS":298,"BLOCK_TRANSACTIONS":1,"BLOCK_L1_SIZE":400,"LOG_DATA":1,"TRM":23,"PRECOMPILE_ECPAIRING_MILLER_LOOPS":298,"SHF":15,"EUC":3,"PRECOMPILE_SHA2_BLOCKS":298,"HUB":16,"EC_DATA":11,"PRECOMPILE_BLAKE_EFFECTIVE_CALLS":298,"PRECOMPILE_ECADD_EFFECTIVE_CALLS":298,"PRECOMPILE_MODEXP_EFFECTIVE_CALLS":298,"MMIO":0,"RLP_TXN":140,"BLOCK_KECCAK":603,"MOD":7,"OOB":5,"MUL":9,"PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS":298,"PRECOMPILE_RIPEMD_BLOCKS":298,"BIN":15,"BLOCK_DATA":13,"RLP_ADDR":7,"PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS":298,"ROM":1,"PRECOMPILE_ECMUL_EFFECTIVE_CALLS":298,"MMU":10,"RLP_TXN_RCPT":91,"BLOCK_HASH":1,"EXP":5,"PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS":298}}}


vs

{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"v0.5.3-beta","blockNumber":6975,"tracesCounters":{"EXT":7,"ADD":1,"LOG_INFO":6,"MXP":3,"TXN_DATA":17,"WCP":45,"ROM_LEX":1,"PRECOMPILE_BLAKE_ROUNDS":83851713,"BLOCK_TRANSACTIONS":1,"BLOCK_L1_SIZE":400,"LOG_DATA":1,"TRM":23,"PRECOMPILE_ECPAIRING_MILLER_LOOPS":83851713,"SHF":15,"EUC":3,"PRECOMPILE_SHA2_BLOCKS":83851713,"HUB":16,"EC_DATA":11,"PRECOMPILE_BLAKE_EFFECTIVE_CALLS":83851713,"PRECOMPILE_ECADD_EFFECTIVE_CALLS":83851713,"PRECOMPILE_MODEXP_EFFECTIVE_CALLS":83851713,"MMIO":0,"RLP_TXN":140,"BLOCK_KECCAK":167703433,"MOD":7,"OOB":5,"MUL":9,"PRECOMPILE_ECPAIRING_G2_MEMBERSHIP_CALLS":83851713,"PRECOMPILE_RIPEMD_BLOCKS":83851713,"BIN":15,"BLOCK_DATA":13,"RLP_ADDR":7,"PRECOMPILE_ECPAIRING_FINAL_EXPONENTIATIONS":83851713,"ROM":1,"PRECOMPILE_ECMUL_EFFECTIVE_CALLS":83851713,"MMU":10,"RLP_TXN_RCPT":91,"BLOCK_HASH":1,"EXP":5,"PRECOMPILE_ECRECOVER_EFFECTIVE_CALLS":83851713}}}

**Comment by letypequividelespoubelles** [comment]
#1120 should fix this, and is merged already +but not in 0.5.3-beta).

**Comment by OlivierBBB** [comment]
@letypequividelespoubelles Do we know if #1120 indeed fixes the issue ?

**Comment by letypequividelespoubelles** [comment]
I'm pretty sure it does, but we need confirmation from @FlorianHuc when he'll test with new release.
