### ISSUE TITLE
`prettyPrint` method for exceptions

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1163]
What would make sense is to write a `prettyPrint` method for exceptions where we print something

```java
underlying OpCode: <mnemonic>
raw exceptions:
  stackUnderflowException: ✅
  stackOverflowException:
  InvalidOpcodeException: 
  MemoryExpansionException ✅
  OutOfGasException: ✅
  ...
  None ✅
```
(we only print the present exceptions along with `None` (the above example makes no sense, it's just an example.)

_Originally posted by @OlivierBBB in https://github.com/Consensys/linea-tracer/pull/1133#discussion_r1754576062_

**Comment by lorenzogentile404** [comment]
addressed in https://github.com/Consensys/linea-tracer/pull/1133.

**Comment by OlivierBBB** [comment]
Can this be closed, then ? @lorenzogentile404
