### ISSUE TITLE
insufficient balance

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1169]
## Ranges

```rust
2746060-2746060
```

# Issue

In mainet with release v0.6.0-rc1:

Name: BLOCK_NUMBER, Length: 84001, dtype: int64
Error fetching or parsing JSON: 'result' {'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32603, 'message': 'Plugin internal error', 'data': 'Exceptions triggered while tracing:\n  - Insufficient balance\n\t\tAddress: 0x2fcb398bcb5bd2aec807941f9d7953e1135056b8\n\t\tBalance: 0x0000000000000000000000000000000000000000000000000000000000000000\n\t\tValue: 0x000000000000000000000000000000000000000000000000006a94d74f430000\n'}}
Failed to fetch or parse JSON data for blockNumber=2746060: 'result'

**Comment by OlivierBBB** [comment]
It blows up for me too.

**Comment by OlivierBBB** [comment]
Related testing issue: https://github.com/Consensys/linea-tracer/issues/1172
