### ISSUE TITLE
Extract Mining Beneficiary from `BlockHeader.getExtraData()`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#1202]
Linea uses the clique consensus protocol (see [EIP-225](https://eips.ethereum.org/EIPS/eip-225#specification)).  The upshot of this is that the mining beneficiary address is embedded in the data field of the block, whilst `coinbase` is set to `0x0`.  Therefore, this part of `ReplayExecutionEnvironment` is incorrect:

```
final TransactionProcessingResult outcome =
            transactionProcessor.processTransaction(
                updater,
                (ProcessableBlockHeader) header,
                tx,
                header.getCoinbase(),
               ...);
```

Specifically, `header.getCoinbase()` does not return the correct beneficiary address.  Instead, we need to extract it from `header.getExtraData()`.   

This explains why various transactions fail with an incorrect balance for the address (see [here](https://github.com/Consensys/linea-tracer/issues/1047#issuecomment-2343684505) for more).

**Comment by OlivierBBB** [comment]
Thanks @DavePearce. I discussed this point with @julien-marchand, too, and the conclusion was that blocks contain `miner=0x000000` which is where we got the coinbase at `0x0` from in our tests. We have to use the address (deduced from the public key) that signed the block instead for both
- the output of the `COINBASE` opcode
- the recipient address of fees

**Comment by DavePearce** [comment]
Completed by #1222
