### ISSUE TITLE
fix(blockhash): `blockhash-into-wcp-lower-bound` lookup and `constency` constraint failing in reference tests

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/besu-sequencer-plugins#1297]

**Comment by lorenzogentile404** [comment]
[failedBlockchainReferenceTests 11.json](https://github.com/user-attachments/files/17113262/failedBlockchainReferenceTests.11.json)

**Comment by letypequividelespoubelles** [comment]
is it linked to https://github.com/Consensys/linea-specification-internal/issues/611

**Comment by letypequividelespoubelles** [comment]
sorry, I meant https://github.com/Consensys/linea-specification-internal/issues/610

**Comment by letypequividelespoubelles** [comment]
duplicate of #1527
