### ISSUE TITLE
Blockchain reference tests 600-627

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1333]
## 600 - 627

- [ ] 600: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`, `traceEndConflation`, `balanceXorByteCodeAddressLoXorExpData2XorHashInfoKeccakLoXorStorageKeyHiXorFromAddressLo has invalid width (256bits)`
- [ ] 601: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 602: `TxnData.currentBlock`
- [ ] 603: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 604: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 605: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 606: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 607: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`, `besu.evm.internal.UnderflowException`
- [ ] 608: `Blockdata.getChainIdFromConflation`,
- [ ] 609: `Blockdata.getChainIdFromConflation`, `Value 672854 cannot be represented as an unsigned short (it is negative or too big)`
- [ ] 610: `Blockdata.getChainIdFromConflation`,
- [ ] 611: `Blockdata.getChainIdFromConflation`,
- [x] #1335

```bash
 RomChunk with:
		address = 0xec0e71ad0a90ffe1909d27dac207f7680abba42d
		deployment number = 3
		deployment status = true
	not found
```

- [ ] 613: `Blockdata.getChainIdFromConflation`,
- [x] 614: success
- [x] 615: success
- [x] 616: success
- [ ] 617: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 618: `Blockdata.getChainIdFromConflation`
- [ ] 619: `Blockdata.getChainIdFromConflation`
- [ ] 620: `Blockdata.getChainIdFromConflation`
- [ ] 621: `Blockdata.getChainIdFromConflation`
- [ ] 622: `Blockdata.getChainIdFromConflation`
- [ ] 623: `Blockdata.getChainIdFromConflation`
- [ ] 624: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`, `txndata` constraints failing in `eip2930_London`
- [ ] 625: `Blockdata.getChainIdFromConflation`, `TxnData.currentBlock`
- [ ] 626: `Blockdata.getChainIdFromConflation`
- [ ] 627: `Blockdata.getChainIdFromConflation`

**Comment by OlivierBBB** [comment]
## 500 - 549

- [ ] 500
- [ ] 501
- [ ] 502
- [ ] 503
- [ ] 504
- [ ] 505
- [ ] 506
- [ ] 507
- [ ] 508
- [ ] 509
- [ ] 510
- [ ] 511
- [ ] 512
- [ ] 513
- [ ] 514
- [ ] 515
- [ ] 516
- [ ] 517
- [ ] 518
- [ ] 519
- [ ] 520
- [ ] 521
- [ ] 522
- [ ] 523
- [ ] 524
- [ ] 525
- [ ] 526
- [ ] 527
- [ ] 528
- [ ] 529
- [ ] 530
- [ ] 531
- [ ] 532
- [ ] 533
- [ ] 534
- [ ] 535
- [ ] 536
- [ ] 537
- [ ] 538
- [ ] 539
- [ ] 540
- [ ] 541
- [ ] 542
- [ ] 543
- [ ] 544
- [ ] 545
- [ ] 546
- [ ] 547
- [ ] 548
- [ ] 549

**Comment by OlivierBBB** [comment]
## 550 - 574

- [ ] 550
- [ ] 551
- [ ] 552
- [ ] 553
- [ ] 554
- [ ] 555
- [ ] 556
- [ ] 557
- [ ] 558
- [ ] 559
- [ ] 560
- [ ] 561
- [ ] 562
- [ ] 563
- [ ] 564
- [ ] 565
- [ ] 566
- [ ] 567
- [ ] 568
- [ ] 569
- [ ] 570
- [ ] 571
- [ ] 572
- [ ] 573
- [ ] 574

**Comment by OlivierBBB** [comment]
## 600 - 527

- [ ] 600
- [ ] 601
- [ ] 602
- [ ] 603
- [ ] 604
- [ ] 605
- [ ] 606
- [ ] 607
- [ ] 608
- [ ] 609
- [ ] 610
- [ ] 611
- [ ] 612
- [ ] 613
- [ ] 614
- [ ] 615
- [ ] 616
- [ ] 617
- [ ] 618
- [ ] 619
- [ ] 620
- [ ] 621
- [ ] 622
- [ ] 623
- [ ] 624
- [ ] 625
- [ ] 626
- [ ] 627

**Comment by lorenzogentile404** [comment]
Outdated tests results.
