### ISSUE TITLE
Blockchain reference tests 575-599

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1340]
## Blockchain reference tests 575-599

- [x] 575 @lorenzogentile404:

```bash
constraints failed:
txndata.verticalisation-rlp-txn-rcpt,
txndata.comparison---gas-limit-must-cover-upfront-gas-cost,
txndata.verticalization,
txndata.total-number-constancies,
txndata.batch-num-increments,
txndata.comparison---final-refund-counter-vs-refund-limit,
txndata.comparison---nonce-must-not-exceed-EIP-2681-max-nonce,
txndata.abs-tx-num-increments,
txndata.counter-column-updates-type-1,
txndata.batchNum-txNum-lexicographic,
txndata.comparison---initial-balance-must-cover-value-plus-maximal-gas-cost, txndata.cumulative-gas,
txndata.comparison---comparing-the-maximum-gas-price-against-the-basefee,
txndata.comparison---detect-empty-data-in-transaction,
txndata.integer-division---compute-upper-limit-for-refunds
```

- [ ] 576: `blockdata.Blockdata.getChainIdFromConflation`, `balanceXorByteCodeAddressLoXorExpData2XorHashInfoKeccakLoXorStorageKeyHiXorFromAddressLo has invalid width (163bits)` in `module.hub.Trace.pAccountBalance`
- [ ] 577: `blockdata.Blockdata.getChainIdFromConflation`, `balanceXorByteCodeAddressLoXorExpData2XorHashInfoKeccakLoXorStorageKeyHiXorFromAddressLo has invalid width (163bits)` in `module.hub.Trace.pAccountBalance`
- [ ] 578: `blockdata.Blockdata.getChainIdFromConflation`, `txndata.TxnData.currentBlock`
- [ ] 579: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 580: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 581: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 582: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 583: `blockdata.Blockdata.getChainIdFromConflation`, `Value 172822 cannot be represented as an unsigned short (it is negative or too big)`, `txndata.TxnData.currentTx`

```java
Exceptions triggered while tracing:
  - Value 172822 cannot be represented as an unsigned short (it is negative or too big)
  - null
```

- [ ] 584: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 585: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 586: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 587: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 588: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 589: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 590: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 591: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 592: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 593: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 594: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 595: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 596: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 597: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 598: `blockdata.Blockdata.getChainIdFromConflation`
- [ ] 599: `blockdata.Blockdata.getChainIdFromConflation`, `txndata.TxnData.currentBlock`

**Comment by lorenzogentile404** [comment]
Outdated tests results.
