### ISSUE TITLE
Implement modulesToCount selection from module limits TOML config

### ISSUE THREAD

**Issue by powerslider** [Consensys/besu-sequencer-plugins#1395]

**Comment by gauravahuja** [comment]
We realised that we do not need a dynamic list of modulesToCount and instead what to trace and count all modules however have a dynamic list of modules to prove. However, after discussion with the prover team we decided to not have a dynamic list of modules to prove either as It is difficult for the prover would need to recreate the public input, update the L1 verifier SMC, etc. So we do as before, ie manually update the list of module to trace/constraints in the makefile when we want to release on sepolia / mainnet.
