### ISSUE TITLE
Cast Exception in `mmu.instructions.RamToExoWithPadding`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#1400]
This line seems to be causing a casting-related exception:

```
 private void row3(final MmuData mmuData) {
    // row n°3
    final Bytes dividend = Bytes.ofUnsignedShort(extractionSize);                <---------
    final EucOperation eucOp = euc.callEUC(dividend, Bytes.of(LLARGE));
```

The exception is:

```
Exceptions triggered while tracing:
- Value 1048575 cannot be represented as an unsigned short (it is negative or too big)
- null
java.lang.RuntimeException:
java.lang.IllegalArgumentException: Value 1048575 cannot be represented as an unsigned short (it is negative or too big)
```

@letypequividelespoubelles --- I can't really judge what's supposed to happen here.

**Comment by letypequividelespoubelles** [comment]
It could be trying to call a precompile with a callDataSize greater than a short, or a transaction callDataSize greater than a short.
Tbh I'm not fond of changing the columns width / type of argumenst just to make one refTest passes
