### ISSUE TITLE
Mega "simple exceptions testing" issue

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1435]
# Main point

We should create tests that trigger, for every single opcode, every single possible exception (including aborting conditions, failure conditions for `CREATE`'s, issues with precompiles.)

# Details

- make tables with one row per opcode and one column per exception and mark a cell iff that opcode can trigger that exception
- write tests that trigger the relevant exception for every such cross

## List of ZKEVM exceptions

```rust
SUX
SOX
MXPX
OOGX
RDCX
JUMPX
STATICX
SSTOREX
ICPX
MAXCSX
OPCX
```

## Accessing `delta` and `alpha`

```java
  public void bla(OpCode opCode) {
    opCode.getData().stackSettings.delta(); // number of items that we pop, ∈ {0, 1, ..., 16 or 17}
    opCode.getData().stackSettings.alpha(); // number of items that we add to the stack; the only thing that matter is whether $\alpha > \delta$ ? Also $\alpha - \delta \leq 1$
  }
```

## `stackUnderflowException`

If an instruction removes $\delta$ many items from the stack there should be $\delta$ many tests where you initially do $0, 1, \dots, \delta - 1$ initial pushes before triggering the opcode.
```
PUSH1 01
PUSH1 02
PUSH1 03
PUSH1 04
SOME_OPCODE
```
You can access $\delta$ through the `OpCodeData`. As suggested by @lorenzo.gentile you can batch these considering the set of all instructions with $\delta = \delta_0$ and go through all **positive** values of $\delta_0$. We can also include the final one (which won't raise an exception.)

```
ArgumentStream1 streamOfDeltas  = List.of(0, 1, ...);
ArgumentStream1 streamOfOpCodes = [just walk through all the opcodes and keep those opcodes that have this delta];
```

## `stackOverflowException`

You just have to do something like
```java
for (i = 0; i < 1024; i++) {
	program.push(i);
}
program.op(OpCode.BLA);
```

## Almost unique instructions

Those two should essentially be already done (though checking it won't hurt):
- RDCX:    can only be triggered by `RETURNDATACOPY` (OOB)
- JUMPX:   can only be triggered by `JUMP` and `JUMPI` (OOB)

Those would be new:
- STATICX: can only be triggered by `CALL`, `SSTORE`, `SELFDESTRUCT`, `LOG's`, `CREATE(2)`, 
- SSTOREX: can only be triggered by `SSTORE`
- ICPX:    can only be triggered by `RETURN` during a deployment
- MAXCSX:  can only be triggered by `RETURN` during a deployment (we may already have stuff in place for this in OOB)
- OPCX:    can only be triggered by `INVALID` and any byte that isn't an opcode.

# Deployment specific exceptions (`MAXCSX` and  `ICPX`)

Wrt `MAXCSX` and  `ICPX` we should test
- small deployment which starts with `0xEF`  (i.e. only `ICPX`)
- large deployment which starts with something else (i.e. only `MAXCSX`)
- large deployment which starts with `0xEF` (i.e. both conditions at once.)

**Comment by lorenzogentile404** [comment]
Note: go through instruction handling of the HUB section of the spec. Some OpCode have specific exceptions, while others are shared (about 11 in total and 6 shared). The tests should be the minimal ones such that they trigger the relevant exception. CALL, RETURN and CREATE may be tricky.

**Comment by lorenzogentile404** [comment]
- [x] SUX
- [x] SOX
- [ ] MXPX (MXP but shorter tests required): all cases covered except OpCode.COPY-type (Type 4) and OpCode.CALL-type (Type 5)
- [ ] OOGX (MXP but shorter tests required, note that MXPX implies OOGX): @OlivierBBB do we need to test OOGX separately?
- [x] RDCX (OOB)
- [x] JUMPX (OOB)
- [x] STATICX
- [x] SSTOREX
- [x] ICPX (still under investigation due to Besu issue)
- [x] MAXCSX (still under investigation due to Besu issue)
- [x] OPCX

**Comment by letypequividelespoubelles** [comment]
Do we want tests that trigger several exception, to be sure we trigger the right tracedException one ?

**Comment by lorenzogentile404** [comment]
@letypequividelespoubelles that seems a good idea, as a second step. @OlivierBBB what do you think?

**Comment by OlivierBBB** [comment]
@letypequividelespoubelles This is the "simple" exceptions suite. The purpose is just to see if all exceptions are doing ok in the HUB and elsewhere (slight exception for deployments, though, see the paragraph on **Deployment specific exceptions**.

**Comment by OlivierBBB** [comment]
@lorenzogentile404 This issue is closed, but what about the OOGX stuff ? **Edit.** My bad, it's continued here https://github.com/Consensys/linea-tracer/issues/1509
