### ISSUE TITLE
modexp_d20g1v0_London 

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1463]
there is a precondition in MmioData l227:

`0 < size && size <= LLARGE`

but in some cases size is 0, hence the precondition fails.

size is set to 0 for instance for :

  ```
private void vanishingMicroInstruction(MmuData mmuData, final int i) {
    mmuData.mmuToMmioInstruction(
        MmuToMmioInstruction.builder()
            .mmioInstruction(MMIO_INST_LIMB_VANISHES)
            .targetLimbOffset(i)
            .build());
  }
```

it's not clear if processing of MmioData with size 0 should not happen at all, or if a new handling is to be added.

Tests: modexp_d20g1v0_London

**Comment by FlorianHuc** [comment]
seems to have similar issue in: modexp_d24g0v0_London

**Comment by letypequividelespoubelles** [comment]
#1497
