### ISSUE TITLE
`ToyExecutionEnvironmentV2` may need to use `EMPTY_VALIDATOR` instead of `DEFAULT_VALIDATOR`

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/besu-sequencer-plugins#1475]
In order to deal with the issue https://github.com/Consensys/linea-tracer/issues/1460, we had to change the following in `ToyExecutionEnvironmentV2`:

```java
  @Builder.Default
  private final TransactionProcessingResultValidator transactionProcessingResultValidator =
      TransactionProcessingResultValidator.EMPTY_VALIDATOR;
  // This was previously DEFAULT_VALIDATOR, however some tests we write are supposed to generate failing transactions
  // Thus we cannot use the DEFAULT_VALIDATOR since it asserts that the transaction is successful
```

The reason is that DEFAULT_VALIDATOR asserts that the transaction is successful, indeed:

```java
@FunctionalInterface
public interface TransactionProcessingResultValidator {

  void accept(Transaction transaction, TransactionProcessingResult transactionProcessingResult);

  TransactionProcessingResultValidator DEFAULT_VALIDATOR =
      (t, r) -> {
        assertTrue(
            r.isSuccessful(),
            () ->
                "Transaction: %s not successful. %s"
                    .formatted(t.getHash().toString(), r.toString()));
      };

  TransactionProcessingResultValidator EMPTY_VALIDATOR = (t, r) -> {};
}
```

However, in some tests we intentionally create failing transactions. @gauravahuja does it make sense to you too?

**Comment by OlivierBBB** [comment]
The main point being: we want tests with failing transactions, we don't expect our tests to produce successful transactions. Thus using the `DEFAULT_VALIDATOR` seems out of place given that it asserts the transaction is successful.

**Comment by gauravahuja** [comment]
You can always override the validator with a new validator that validates the specific case in the test. You can do that when you build the ToyExecutionEnvironment.

**Comment by gauravahuja** [comment]
```
ToyExecutionEnvironmentV2.builder()
            .transactionProcessingResultValidator(<custom validator>)
            .accounts(accounts)
            .transaction(tx)
            .build();
```

**Comment by OlivierBBB** [comment]
The default validator should be what is currently called the `EMPTY_VALIDATOR` in the sense that we have no expectation as to the success or failure of the execution of random tests.

**Comment by gauravahuja** [comment]
Closing since this was fixed in https://github.com/Consensys/linea-tracer/pull/1450/files#diff-54648132e58942b7e87e12d79363a189276e7b7d74a7a730e78e7ad395b45bbeR58
