### ISSUE TITLE
modexp_d20g0v0_London size has value 0.

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1497]
Multiple reference tests wials with error "size has value 0." which comes from checks in MmioData where size is expected to be positive.

**Comment by letypequividelespoubelles** [comment]
I will check once https://github.com/Consensys/linea-tracer/pull/1473 is merged.

**Comment by letypequividelespoubelles** [comment]
67 tests failing for `blockchainrefTest_200`
