### ISSUE TITLE
BlakeSubsection null

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1516]
in test CALLBlake2f.json, we try to create a BlakeSubsection but it fails because there isn't enough gaz:

 blakeSuccess = wellFormedF && sufficientGas = true && false = false;
 
 but then the condition:
 
 checkArgument(blake2fParamsOobCall.isRamSuccess() == blakeSuccess);
 
 
is not verified, throw an exception. This lead to the blakeSubsection not being  instantiated and later to an NPE.

Is the check correct? Or should we set success to false in blake2fParamsOobCall = new Blake2fParamsOobCall(calleeGas); ?

**Comment by FlorianHuc** [comment]
or maybe it's an issue with the gas calculation

**Comment by letypequividelespoubelles** [comment]
fixed in the linked PR
