### ISSUE TITLE
wrong calculation for numberMmioInstructions

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1517]
numberMmioInstructions is computed as:

  public int numberMmioInstructions() {
    return totalLeftZeroesInitials + totalNonTrivialInitials + totalRightZeroesInitials;
  }

but it happens it can be bigger. This seems to happen when going through MLoad L89:  public MmuData setMicroInstructions(MmuData mmuData) {

where we set two microinstructions while we have totalNonTrivialInitials 1 only:

Issue is in:

      case MMU_INST_BLAKE -> {
        mmuData = blake.preProcess(mmuData);
        yield blake.setMicroInstructions(mmuData);
      }
      
   blake.preProcess   code set this to one but then we enter, setMicroInstructions we add two of them

**Comment by letypequividelespoubelles** [comment]
which test is breaking ? 

edit: I fix the typo and added some more test for BLAKE precompile call, will debug it. It's true we didn't have unit test for BLAKE :(
