### ISSUE TITLE
fragment is null

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#1518]
modexp_modsize0_returndatasize_d4g0v0_London[London]

in callsection we do: this.addFragment(finalContextFragment); with finalContextFragment == null.

This later leads to an NPE while looping over all elements.

we are in case where scenarioFragment.getScenario() == CALL_PRC_FAILURE

We may need a new condition in the constructor.

**Comment by letypequividelespoubelles** [comment]
same as #1502

**Comment by letypequividelespoubelles** [comment]
seems fixed now
