### ISSUE TITLE
Reenable Tx Outcome Checks

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#1521]
The goal here is to undo the temporary fix in #1520.  The problem is that a change in the BESU version (which fixed a bug with traceEndTransaction) has meant that all recorded tx outcomes are potentially invalid with respect to e.g. the sender.  The temporary fix in #1520 simply disabled tx outcome checks.  The goal now is to update the recorded tx outcome information so that the tests will pass with outcome checking enabled.

**Comment by DavePearce** [comment]
@letypequividelespoubelles Why did you close this?  This is my reminder to fix the outstanding problems!

**Comment by letypequividelespoubelles** [comment]
sorry, my bad

**Comment by DavePearce** [comment]
- [x] Include improved Capture Debugging
- [x] Rename existing replay files
- [x] Remove unused replay files
- [x] Check diffs
- [x] Copy over new replay files
- [ ] Tag missed tests? `LeosNewRanges` and `LeosNewRangesSplitTests`
- [ ] Test test test!
