### ISSUE TITLE
BLOCK_DATA update

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#1603]
# Main point

We need to modify the BLOCK_DATA module to support for variable (higher) BLOCK_GAS_LIMIT.

# Details

The BLOCK_DATA module should verify that the BLOCK_GAS_LIMIT `H_l` satisfy the following properties, for every block in the conflation:

```
H_l < H_l' + q
H_l > H_l' - q
H_l < 2_000_000_000
H_l ≥ 61_000_000

q := H_l' / 1024
```

In the above `H_l'` is the preceding BLOCK_GAS_LIMIT. The above thus requires `b + 1` BLOCK_GAS_LIMIT's, starting with the latest `BLOCK_GAS_LIMIT` from the last conflation. There will be some call's to WCP and MOD.

**Comment by letypequividelespoubelles** [comment]
@OlivierBBB instead of calling MOD, we should call EUC, every inputs will be < 8 bytes long.
