### ISSUE TITLE
Implement rollup_getTracesCounters

### ISSUE THREAD

**Issue by macfarla** [Consensys/besu-sequencer-plugins#179]
This method is intended to be used for recovery purposes to replay the traces counting for a block previously created and already in the canonical chain, e.g coordinator crash, bug in zkBESU traces counting.

rollup_getTracesCountersByBlockNumberV1(blockNumber, expectedTracesEngineVerision)

Parameters:
blockNumber: String - decimal encoded integer of the start block number
expectedTracesEngineVersion: String - version of expected traces version system. If the runtime version is not the expected version, an error shall be returned. In case of traces being cached, if cached version is not the same as expected one, new traces shall be generated. 

Response: Object
result: Object - with
- tracesCounters: Object with moduleName: number of lines per module
- tracesEngineVersion: String - version of traces module

error: Object with error info
- type: an enum of possible errors.
- message: Detail error message

**Comment by non-fungible-nelson** [comment]
Unblocked via close of Protocols-Misc#746

**Comment by Ludcour** [comment]
Sorry I should have asked you in the meeting @macfarla what's the update on this please?

**Comment by Ludcour** [comment]
Shall we consider this ticket as done and then iterate on the issues we may continue to face regarding differences between geth counting and besu counting?

**Comment by macfarla** [comment]
agree @Ludcour
