### ISSUE TITLE
BLAKE2f

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#307]
**BLAKE2f**

Single module (no info/data)
- triggered _iff_ size = 213
- receives 213 data bytes (vertically)
- extracts
  - r
  - data
  - f
- receives from HUB
  - gas_cost (=g_r, **prediction**)
  - gas_stipend
  - PREC_OOGX bit (gas_cost > gas_stipend, **prediction**)
- predicts output (vertically)

**Comment by powerslider** [comment]
Task will be closed due to this functionality being transferred to the OOB module.
