### ISSUE TITLE
Tracking exceptional blocks + unit test extraction

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#352]
# Main point

It arose in discussion with @FlorianHuc that we should track those mainnet / testnet blocks that produced mistakes in the arithmetization / the tracer and (if applicable) extract unit tests from them. This issue could be a first step in that direction, i.e. a compendium of those exceptional blocks + description of the issue + fix.

**Comment by FlorianHuc** [comment]
BLOCK 931834-0xe156398e9c8dbe793016cb3d69eb8062290ab15058437a8b8ae223419a27c3fb DIFFERED | PRECOMPILE_ECRECOVER: 53 vs 54

BLOCK 927334-0x26827885d5c7409a19912bb3317adf06159c718c03b6dca24efebbfaf6e20c94 DIFFERED | BLOCK_L1SIZE: 76086 vs 84255 | PRECOMPILE_SHA2: 9 vs 4

BLOCK 927340-0xe8029e23694ddc644c1a48356dd8fdf54702d916f0f1ce380f1485266a044449 DIFFERED | ADD: 52210 vs 52194 | BLOCK_L1SIZE: 75948 vs 81735

BLOCK 922278-0xd061449b1d2b54a9737b8c7c63766a35ea3ac5a2e5d6c1ecb8822088d16d3591 DIFFERED | BLOCK_L1SIZE: 151194 vs 79635 | BLOCK_TX: 378 vs 189 | BLOCK_KECCAK: 4735 vs 4762

BLOCK 350557-0xc669be3eeb35ca079b528de7b856a751cd12e5497746783553ee73ed1af9357a DIFFERED | ROM: 14436 vs 25218

BLOCK 352238-0xd5db7956bb8ebd757273954fa1640ba7bc6367e08dd7a1f750999a626fbb132e DIFFERED | ROM: 34 vs 66

BLOCK 350557-0xc669be3eeb35ca079b528de7b856a751cd12e5497746783553ee73ed1af9357a DIFFERED | ROM: 23170 vs 25218

BLOCK 35774-0x9128ec3713a7c19bff5064f1d018a34178cfe65798f65e8456075acaef8d2c7b DIFFERED | EXT: 80 vs 81

BLOCK 29838-0x62b1baf5f2c9b52596987c35165a4de733e9d36aa667103b292882c3fd363a5c DIFFERED | BLOCK_TX: 2 vs 1 | MOD: 8 vs 8 | RLP_ADDR: 7 vs 8

BLOCK 29839-0x0c31b0f85767bda03a284503873b182b9495014b4a3bb4c1c7573608c8945d9a DIFFERED | EXT: 8 vs 9 | BLOCK_TX: 2 vs 1 | PRECOMPILE_ECRECOVER: 0 vs 1 | RLP_ADDR: 7 vs 8

BLOCK 29314-0xe96852943f749d46f7120d2854bece21e4f4a460e06888ea8f34d70eaa561e03 DIFFERED | PUB_LOG: 29 vs 14 | BLOCK_TX: 2 vs 1 | MOD: 32 vs 16 | RLP_ADDR: 7 vs 8 | MMU: 10 vs 188 | PUB_LOG_INFO: 11 vs 1

BLOCK 29315-0x20f887e65da912300ff085fd3e02442447e376412cd469dd6f6f2c20ccc4dfd3 DIFFERED | PUB_LOG: 45 vs 22 | BLOCK_TX: 2 vs 1 | MOD: 80 vs 32 | RLP_ADDR: 7 vs 8 | MMU: 10 vs 370 | PUB_LOG_INFO: 21 vs 2

BLOCK 27694-0xef41fd22b14c1246b4af481f408642c55d6ae6ef1199e46ad0d900e7ab5ad227 NOT MATCHED: EXT: 7 vs 8 | ADD: 849 vs 850 | MXP: 281 vs 282 | WCP: 738 vs 434 | PUB_LOG: 45 vs 22 | SHF: 95 vs 96 | HUB: 3337 vs 2369 | BLOCK_TX: 2 vs 1 | MOD: 79 vs 32 | MUL: 13 vs 14 | ROM: 34209 vs 20930 | MMU: 10 vs 370 | PUB_LOG_INFO: 21 vs 2
