### ISSUE TITLE
CLI options for L2L1 bridge

### ISSUE THREAD

**Issue by delehef** [Consensys/besu-sequencer-plugins#480]
L2L1 bridge contract address & log topic ought to be specified by CLI arguments rather than environment variables.

**Comment by delehef** [comment]
@fab-10 could you please help with this one?

We would need the `ZkTracer` to potentially receive two CLI arguments:
 - `L2L1topic`: hex string;
 - `L2L1_CONTRACT_ADDRESS`: hex string.

The new `ZkTracer(final String l2l1ContractAddress, final String l2l1Topic)` constructor is ready on [this PR](https://github.com/Consensys/besu-sequencer-plugins/pull/591), would you mind taking it from there and adding the CLI switch?

**Comment by delehef** [comment]
No

**Comment by fab-10** [comment]
ok, so will make them mandatory
