### ISSUE TITLE
investigate why PRECOMPILE_SHA2 is biggger

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#492]
for instance, we have  PRECOMPILE_SHA2 bigger in besu than geth (9 > 4) for BLOCK 2001073-0x11ee9e924f2a15d7ea46bfcfdde24ba5257b3f8dd607e43500f8f0922769b413.

They are expected to be equal.

**Comment by FlorianHuc** [comment]
One with a big difference:

BLOCK 2646298-0x24002fef5bdeb5f7cd6a92081ceb6a31ab3e2ca6b4119279d06dfcb3c2c47d5e DIFFERED: PRECOMPILE_SHA2: 896 > 42

**Comment by FlorianHuc** [comment]
[2646298-0x24002fef5bdeb5f7cd6a92081ceb6a31ab3e2ca6b4119279d06dfcb3c2c47d5e-v0.2.0.json.gz](https://github.com/Consensys/besu-sequencer-plugins/files/13700573/2646298-0x24002fef5bdeb5f7cd6a92081ceb6a31ab3e2ca6b4119279d06dfcb3c2c47d5e-v0.2.0.json.gz)

**Comment by letypequividelespoubelles** [comment]
add a counter for nb of call and effective call (ie without exception, etc) :
https://github.com/Consensys/besu-sequencer-plugins/pull/459/commits/fb70845eb913078ef0b437642bb7354affb92419
https://github.com/Consensys/besu-sequencer-plugins/pull/459/commits/613f4b01f7f7cc7877e7fd9782b5afea55423db0

**Comment by FlorianHuc** [comment]
Geth was counting the raw number of precompile call while besu will count the number of effective calls, and potentitally add some weighting.

A new counter has been added for all precompile to replicate Geth behaviour.
