### ISSUE TITLE
explain PRECOMPILE_ECRECOVER difference

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#493]
Besu counted one line less than geth for:

 BLOCK 931834-0xe156398e9c8dbe793016cb3d69eb8062290ab15058437a8b8ae223419a27c3fb DIFFERED | PRECOMPILE_ECRECOVER: 53 vs 54

**Comment by delehef** [comment]
Geth does not account for invalid calls to ECRECOVER (`gasPaid = 1039 < 3000`), whereas Besu does.
