### ISSUE TITLE
can RLP_ADR counting in Besu be made closer do Geth counting

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#495]
Check if there are events counted in Besu and not in Geth which can be removed from Besu counting.

**Note:** There should be 2 reasons for discrepancies between the two implementations:
- fundamental changes in the arithmetization where a single operation takes a different number of rows in old RLP_ADDR vs new RLP_ADDR, the ratio of number of rows depending on the "recipe" used for producing the RLP string (CREATE vs CREATE2)
- more operations being traced in Besu (related to deployment transactions i.e. transactions with $\texttt{to} = \varnothing$.)

The idea would thus be to (temporarilty) remove these RLP_ADDR calls from Linea to see if the line ratio between the old implementation and new implementation is predictable in terms of the changes in the arithmetizations.

**Comment by delehef** [comment]
[Addressed here](https://github.com/Consensys/besu-sequencer-plugins/pull/459/commits/b499726797a2f498c20005731f48eaaa81fecbdb) by @letypequividelespoubelles, require testing on erroneous blocks.

**Comment by letypequividelespoubelles** [comment]
Can we close the issue ?
