### ISSUE TITLE
Investigate why PRECOMPILE_ECRECOVER can be one smaller

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#501]
BLOCK 941540-0x093969db8f05767b0e9bf7d352a3e4aa99d7dce55e5c84b3b1849f5930a31ccd DIFFERED: PRECOMPILE_ECRECOVER: 41 < 42

**Comment by FlorianHuc** [comment]
[2646298-0x24002fef5bdeb5f7cd6a92081ceb6a31ab3e2ca6b4119279d06dfcb3c2c47d5e-v0.2.0.json.gz](https://github.com/Consensys/besu-sequencer-plugins/files/13700619/2646298-0x24002fef5bdeb5f7cd6a92081ceb6a31ab3e2ca6b4119279d06dfcb3c2c47d5e-v0.2.0.json.gz)

**Comment by FlorianHuc** [comment]
[941540.json.gz](https://github.com/Consensys/besu-sequencer-plugins/files/13700622/941540.json.gz)

**Comment by powerslider** [comment]
Can you please elaborate on which environment have you captured the data?

**Comment by delehef** [comment]
@FlorianHuc most probably the same as [this one](https://github.com/Consensys/besu-sequencer-plugins/issues/493); should I explore further?

**Comment by FlorianHuc** [comment]
can we get a counter ECRECOVER_VALID_AND_INVALID_CALLS that would count the invalid calls as well?

**Comment by letypequividelespoubelles** [comment]
> can we get a counter ECRECOVER_VALID_AND_INVALID_CALLS that would count the invalid calls as well?

 This is already what `PRECOMPILE_ECRECOVER` does, while `PRECOMPILE_ECRECOVER_EFFECTIVE_CALL` counts only valid calls. Can we close the issue ?

**Comment by letypequividelespoubelles** [comment]
> Why would we do that?

Because Geth was counting all the calls, valid and invalid no ?

**Comment by delehef** [comment]
Agreed; but AFAIU, we need the geth-like wrong counting on this branch, the real counting on master, but I don't see why we would need both the real and wrong on this one?
