### ISSUE TITLE
transaction count is wrong when a transaction is not included

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#546]
When the sequencer build a block, if a transaction is not included, it's line counting is not properly reverted.

**Comment by jonesho** [comment]
Details: https://www.notion.so/consensys/Line-counts-mismatch-e6f558cde25c4642a07e215eb4a9b870

**Comment by jonesho** [comment]
Fixed in https://github.com/Consensys/besu-sequencer-plugins/releases/tag/v0.1.4-test10

**Comment by jonesho** [comment]
Fix PR: https://github.com/Consensys/besu-sequencer-plugins/pull/459

**Comment by jonesho** [comment]
Latest plugin tag for the fix: https://github.com/Consensys/besu-sequencer-plugins/releases/tag/v0.1.4-test11

**Comment by FlorianHuc** [comment]
deployed with test10
