### ISSUE TITLE
Add post block creation data size verification

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#556]
If a block includes too much data it can't be finalized.
Therefore, we want to add a second check post all tx have been selected and before the block is finalized to verify the block l1 data size is below the limit.

It should not rely on previoulsy calculated data, instead it should recompute it from scratch. 

It should pop tx if it's not the case until it become true.

**Comment by delehef** [comment]
Shall we close this one?
