### ISSUE TITLE
max time allowed for tx selection

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#559]
The option Xpoa-block-txs-selection-max-time is not taken into account properly.

**Comment by fab-10** [comment]
Fixed in delivery-12 https://github.com/Consensys/linea-besu/releases/tag/delivery-12

*Note*: that in this release the option is now stable and so need to be renamed to `poa-block-txs-selection-max-time` (without the `X` prefix)
