### ISSUE TITLE
Debug EXP module

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/besu-sequencer-plugins#687]
Two tests are failing in EXP module:
- `testModexpLogFFBlockWithLDCase()`;
- One test of the `testModexpLog()` family fails due to the constraint `exp-justify-hub-prediction-modexp-log`;

**Comment by letypequividelespoubelles** [comment]
@lorenzogentile404 can we close it ?

**Comment by OlivierBBB** [comment]
@lorenzogentile404 can we close this one, now ?
