### ISSUE TITLE
Zktracer loads the OpCodes for each initialization

### ISSUE THREAD

**Issue by ahamlat** [Consensys/besu-sequencer-plugins#716]
When doing load testing on eth_sendRawTransaction with transaction simulation enabled, we've noticed that ZkTracer takes more than 20% of the time, on loading the opcode and the spillings.
This is because the OpCodes.load(), reads data from the configuration file for each inititalization of ZkTracer.

<img width="1418" alt="image" src="https://github.com/Consensys/linea-arithmetization/assets/5099602/63c73267-a516-4cea-84f8-7be28f4f31ba">

**Comment by letypequividelespoubelles** [comment]
is it still the case @ahamlat @lu-pinto  ?

**Comment by ahamlat** [comment]
This is fixed, let me close it.
