### ISSUE TITLE
fix(ecdata): trigger it by ec limit counting-only module

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/besu-sequencer-plugins#736]
From Slack:

> for ecdata, why is isn't triggered by the ec*limit counting-only module ?
> For precompile, we have 2 types of modules. One is the limit modules, they count the number of call of successful call to a precompile, and count all the different prover's limit
> The check that the data is of the right size, etc is made here. So imho, ECData (which stores the info) should be called by the limit modules

**Comment by letypequividelespoubelles** [comment]
done, but with reverse logic
