### ISSUE TITLE
verify replayTest works as intended

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#764]
originally posted [here](https://github.com/Consensys/linea-constraints/issues/223) :

>Does it capture everything ? Do we make snapshots of accounts for:
    aborted CALL's / CREATE's ?
    failure condition CREATE's ?
    exceptional BALANCE / EXTCODEXXX / ... ?
    other edge cases ?
    SSTORE / SLOAD

- [ ] @OlivierBBB go through the list of opcodes to see if the above captures everything.

**Comment by OlivierBBB** [comment]
**Question:** do we capture the BLOCKHASH values too ?

**Comment by letypequividelespoubelles** [comment]
> **Question:** do we capture the BLOCKHASH values too ?

No : #935
