### ISSUE TITLE
Publish `linea-arithmetization` artifact build from `temp/issue-248/count-stack-only` branch

### ISSUE THREAD

**Issue by fab-10** [Consensys/besu-sequencer-plugins#778]
since the `ZkTracer` code is now removed from the `linea-sequencer` repo (https://github.com/Consensys/linea-sequencer/pull/15#issuecomment-2178189830), the `linea-sequencer` plugin now depends on `linea-arithmetization` published artifact.

Since for releases we still depends on code from the `temp/issue-248/count-stack-only` branch (see this comment https://github.com/Consensys/linea-sequencer/pull/15#issuecomment-2178189830), a `linea-arithmetization` artifact needs to be build and published from that branch, so it can be used when preparing a new `linea-sequencer` release.

**Comment by powerslider** [comment]
@fab-10 is this task already taken care of? Can we close it?

**Comment by fab-10** [comment]
this has been implemented in branch https://github.com/Consensys/linea-sequencer/commits/release-v0.1.4-testX
