### ISSUE TITLE
We can't generate Trace.java because of `CorsetExist` issues

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#794]
If we comment the corsetExist as to run the test, it still doesn't work

**Comment by DavePearce** [comment]
This is an issue when trying to regenerates `Trace.java` files from IntelliJ, right?  How do you try and do that?  I have been doing it from the command-line with e.g. `./gradlew add` to regenerate the `Trace.java` file for the `add` module.

**Comment by DavePearce** [comment]
I was able to recreate the original problem on my laptop.  However, I then managed to fix it (after some playing around).  I did not need to change anything in the repository itself.  I think it is perhaps a gradle caching issue.  So, one thing to try is removing the `.gradle` directory.

**Comment by DavePearce** [comment]
@powerslider Ok, here is my suggested procedure:

```
rm -r .gradle
./gradlew --stop
./gradlew add
```

And it should work.
