### ISSUE TITLE
`HUB` has to defer `MMU` calls at PostTransactionDefers

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#810]
Because MMUs call for LOG are defered at endTx, and MMU must be called in the same order as the HUB trace it in  order to not break the MMU_STAMP in the lookup HUB into MMU.
Only for the call at TxInit we can call it at execution time.

**Comment by letypequividelespoubelles** [comment]
- [X] LOGX
- [X] MLOAD (https://github.com/Consensys/linea-arithmetization/pull/748/commits/cbe0830f540deed45c5a2c5115e8734a9c3f1aea)
- [X] MSTORE (https://github.com/Consensys/linea-arithmetization/pull/748/commits/cbe0830f540deed45c5a2c5115e8734a9c3f1aea)
- [X] MSTORE8 (https://github.com/Consensys/linea-arithmetization/pull/748/commits/cbe0830f540deed45c5a2c5115e8734a9c3f1aea)
- [X] CALLDATALOAD (https://github.com/Consensys/linea-arithmetization/pull/748/commits/cbe0830f540deed45c5a2c5115e8734a9c3f1aea)
- [x] RETURN
- [x] SHA3 (https://github.com/Consensys/linea-arithmetization/pull/748/commits/d79ef48ba52de74c3cc8910fb9f773d34becda28)
- [x] CREATE(s)
- [x] REVERT
- [x] CALLDATACOPY (https://github.com/Consensys/linea-arithmetization/pull/748/commits/0a5333eef10cb52bb0e45aca4ca6a04a5f51f971)
- [x] RETURNDATACOPY (https://github.com/Consensys/linea-arithmetization/pull/748/commits/0a5333eef10cb52bb0e45aca4ca6a04a5f51f971)
- [x] CODECOPY (https://github.com/Consensys/linea-arithmetization/pull/748/commits/0a5333eef10cb52bb0e45aca4ca6a04a5f51f971)
- [x] EXTCODECOPY (https://github.com/Consensys/linea-arithmetization/pull/748/commits/0a5333eef10cb52bb0e45aca4ca6a04a5f51f971)
- [x] precompile's 
- [X] TRANSACTION_CALL_DATA_DATA to fictitious CN : no need

**Comment by powerslider** [comment]
@letypequividelespoubelles we should re-discuss this with an alternative option of tracing logs all the time and adding a bit to the LogSection to tag the ones that should be reverted and not traced by MMU/MMIO/EUC/WCP.
cc: @OlivierBBB

**Comment by letypequividelespoubelles** [comment]
cf https://github.com/Consensys/linea-arithmetization/issues/844

done https://github.com/Consensys/linea-arithmetization/pull/748
