### ISSUE TITLE
Optimise Trace Generation (Except Hub)

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#837]
The `Trace.java` file produced by `corset` for all of the modules is very inefficient places.  Some examples:

* Every `i8` requires `2` bytes per element (i.e. `16` bits)
* Every `i32` requires `8` bytes per element (i.e. `64` bits)
* Every `i64` requires `32` bytes per element (i.e. `256` bits)

For more details, see [Corset issue#160](https://github.com/Consensys/corset/issues/160).

At this stage, we don't have to do all the modules in one go.  In particular, I will not update the hub with this issue, but will leave that for future.

**Comment by DavePearce** [comment]
So, for the `531` trace files generated from running the tests in this repository.  Originally, they produced `6.7G` of data; now with all modules except `hub` updated, they produce `5.1G` of data.  Its definitely an improvement, though I was hoping for more :). I guess the `hub` is a big part of the reason here.

**Comment by letypequividelespoubelles** [comment]
I(ve updtated the HUB trace in https://github.com/Consensys/linea-arithmetization/pull/748
