### ISSUE TITLE
`ToyWorld` issues

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#840]
List of known issues with our tests. They seem to be related to the `ToyWorld` but we don't know exactly what's going wrong.
- [ ] coinbase address not recognized as such, in particular when it comes to paying the COINBASE address in gas fees at the end of the transaction it's not done for some reason, see #767
- [x] failures when regenerating `Trace.java` files (I believe this was settled by @DavePearce and @letypequividelespoubelles ?) see see https://github.com/Consensys/linea-arithmetization/issues/794#issuecomment-2232440935
- [x] deployment transactions (i.e. `tx.toAddress` is empty) don't run the provided initialization code https://github.com/Consensys/linea-tracer/blob/8fb4af6fa7713dea98ec351cd14626a181acd798/arithmetization/src/test/java/net/consensys/linea/zktracer/instructionprocessing/ContractModifyingStorageTest.java#L180
- [ ] for deployments again there are more layers of `WorldUpdater`'s (4 initially, now 3 for some reason) than expected
- [x] #967
- [x] make the `ToyWorld` aware of precompiles (solved by @OlivierBBB in Tbilissi)
- [x] #997
  - [ ] re-enable `HUB` constraints (uncomment them in the constraints repo's `Makefile`
  - [ ] recompile the zkevm.bin object (`make zkevm.bin -B`)
  - [ ] run some of the simpler tests in the repo (add test, 1+1=2, ...)

**Comment by letypequividelespoubelles** [comment]
@OlivierBBB @gauravahuja I think it's now all ok with @gauravahuja 's ToyV2 ?
