### ISSUE TITLE
Fix `corsetExists` task

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#845]
There appear to be some issues with the `corsetExists` task.  However, its hard to diagnose without being able to reproduce the problem.  It seems that in many places the `dependsOn corsetExists` flag has been commented out (presumably as a workaround).  My feeling is that the sequence of events is:

* The `corsetExists` task fails (for some reason)
* The failure is cached.
* Because the task has no inputs, it is always marked "UP-TO-DATE".

Therefore, we could solve this by including this flag:

```
outputs.upToDateWhen { false }
```

It should also be possible to override the problematic behaviour using `--rerun-tasks`.

**Comment by DavePearce** [comment]
**UPDATE**:  I cannot seem to recreate the original problem unfortunately, which means I cannot test the solution is a solution.

**Comment by powerslider** [comment]
We have tested that if you remove your local Gradle cache, it might work, although it is not verified in all cases:
`rm -rf ~/.gradle`

**Comment by letypequividelespoubelles** [comment]
Thanks to @DavePearce , if someone has the issue, run 

```
rm -r .gradle
./gradlew --stop
./gradlew add
