### ISSUE TITLE
ROM_LEX triggering without signals

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#851]
# Main point

The triggering of the ROM_LEX module should (?) be done by the relevant section / module directly rather than through a signal.
- [x] EXTCODECOPY
- [x] CALL's
- [x] CREATE's
- [x] RETURN
- [x] transaction provided initialization codes from the RLP_TXN module (done at traceStartTx)

**Comment by letypequividelespoubelles** [comment]
done in https://github.com/Consensys/linea-arithmetization/pull/748
