### ISSUE TITLE
Tracing issues list

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#865]
# Main point

This issue is about **understanding with pinpoint accuracy the exact chronology of events in Besu**. Details matter tremendously to the tracer as we would like to rely less and less on "hand modified snapshots".

## CREATE related

- [x] #866
- [x] #867
- [x] #887 

## CALL related

- [x] #868
- [x] #869
- [x] #885

### Memory operations

- [x] #913

### Stack updates

- [x] #872
- [x] #883

### What has already taken place at ... ?

- [x] #870
- [x] #875

### Misc

- [x] #882 
- [x] #871

**Comment by OlivierBBB** [comment]
Our reason for asking is that:
- #866 and #867: for failure condition and empty init code we would like to take snapshots of the updated creator and createe accounts when the TraceContextReEntry hook is activated. This only makes sense if we actually enter a new context in those "trivial" cases
- If not "re-entry" takes place we must hook somewhere else ... maybe post execution of the current OpCode ... or even PreExecution of the next OpCode ... ?

**Comment by non-fungible-nelson** [comment]
Hi @OlivierBBB - there are a bunch of issues opened / questions answered above. I want to make sure I am appropriately tracking next steps, what are they as of now? 

CC: @lu-pinto

**Comment by macfarla** [comment]
ref https://github.com/hyperledger/besu/issues/7301
