### ISSUE TITLE
Which actions have already taken place when one invokes `TraceEndTransaction` ?

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#875]
> Is `TraceEndTransaction` the equivalent (for transaction stopping) to `TraceContextExit` ? What actions are performed between `TraceContextExit` and `TraceEndTransaction` ?

When we want to resolve some `PostRollBackDefers` that should happen after the root context of the transaction reverts (i.e. the whole transaction reverts) but before the transaction is finalized (balance refunds, coinbase fee collection, ...) where do we plug ourselves in ?

**Comment by lu-pinto** [comment]
It does look like `traceBeforeRewardTransaction` could potentially be used. Coinbase fee is only updated after, however the sender gets balance refunded before.

Maybe you will have to cache a snapshot of the last `traceContextExit` or we could add some custom trace methods in for the refunding and rewards part? @daniellehrner  what do you think?

**Comment by OlivierBBB** [comment]
@lu-pinto I'm currently fixing our "transaction finalization" constraints. The `TraceEndTransaction` seems to be the culprit in the errors we see. The problem I'm facing is that at `TraceEndTransaction` the sender account didn't get reimbursed yet ... 🌶️ 

I guess my question would be: what is the right moment to "grab" the final balances of sender, recipient and coinbase _but before_ SELFDESTRUCT's have been acted upon (e.g. if the COINBASE or recipient selfdestructs.)

**Comment by OlivierBBB** [comment]
Some more details:
- we get the wrong balance for the sender at `traceEndTransaction` i.e. no refunds have been granted
- we get the same (wrong) balance at `tranceEndBlock` we can't directly access the balance, but using the `messageFrame.getWorldUpdater` we can look at the sender address and still find the wrong balance
- at `traceEndConflation`, though, the balance has been updated ...

Things are different for the `coinbase` address ... there the updates have happened at the time of the `traceEntTransaction` ...

One hypothesis we were curious about was whether this had something to do with the fact that we are manipulating a `WorldUpdater`, but the fact that things work out fine for the `coinbase` doesn't get with that ...

**Comment by OlivierBBB** [comment]
So wrt the it seems that it gets reimbursed at `trraceContextExit`. This is suggested by this

![image](https://github.com/user-attachments/assets/d563a380-37a5-4c05-8c8a-46acd0c3c5de)

This is a portion of the trace associated with a transaction calling bytecode that is simply `POP`, we transfer 1 Wei and have a gas price of `8 = 1 + 7`, `7` being the `LINEA_BASE_FEE`.

**Comment by OlivierBBB** [comment]
Balance transfers associated with CALL's and CREATE's are done in the `start` method as follows:
```java
  public void process(final MessageFrame frame, final OperationTracer operationTracer) {
    if (operationTracer != null) {
      if (frame.getState() == MessageFrame.State.NOT_STARTED) {
        operationTracer.traceContextEnter(frame);
        start(frame, operationTracer);
      }
```
See in [Besu](https://github.com/hyperledger/besu/blob/22a570eda42dd4bba917bcaac93bdf642fe765fd/evm/src/main/java/org/hyperledger/besu/evm/processor/AbstractMessageProcessor.java#L190).

The main point being that `traceContextEnter` happens before. However, for some reason the warming of the createe has already taken place. See `AbstractMessageProcessor` class.

The same pattern seems to be at play when invoking `traceContextExit`:
```java
  public void process(final MessageFrame frame, final OperationTracer operationTracer) {

    // ...

    if (frame.getState() == MessageFrame.State.COMPLETED_SUCCESS) {
      if (operationTracer != null) {
        operationTracer.traceContextExit(frame);
      }
      completedSuccess(frame);
    }
    if (frame.getState() == MessageFrame.State.COMPLETED_FAILED) {
      if (operationTracer != null) {
        operationTracer.traceContextExit(frame);
      }
      completedFailed(frame);
    }
```

**Comment by OlivierBBB** [comment]
Both the `start` and `completedSuccess` / `completedFailed` are where the balance transfers are done. And for some reason the warmth update is done ahead of time in both cases. One very simple solution for us would be to have a `traceContextExitCompletion` or so to which we would hook ourselves.

**Note.** This issue will also affect the way that we `CALL` and `CREATE`.

**Comment by DavePearce** [comment]
@OlivierBBB Which test(s) is this happening for? It sounds similar to some issues I debugged for the replay tests.

**Comment by OlivierBBB** [comment]
It happens on every single test @DavePearce. What is especially surprising is that
- the COINBASE address gets its gas refund at `traceEndTransaction`
- the sender gets its value refund at `traceEndTransaction`
- but the sender only gets its gas refund much later (it happens between `traceEndBlock` and `traceEndConflation`

**Comment by DavePearce** [comment]
@OlivierBBB So, to clarify, you are seeing this behaviour on the replay tests as well?  If so, do you have some failing block numbers I can investigate?

**Comment by OlivierBBB** [comment]
Sorry for the imprecision @DavePearce, I meant to say: we get that behaviour on all custom tests we wrote. I haven't run them in a bit but I believe we saw this on the Ethereum Reference Tests. I have tested it on the `Issue1031Tests` replay test which produced the same result. I imagine that it's true for all replay tests.

**Comment by OlivierBBB** [comment]
Also I should add: these are `HUB` constraints blowing up. So you have to be running the `HUB` constraints to see it happen.

**Comment by DavePearce** [comment]
@OlivierBBB 

>  I have tested it on the Issue1031Tests replay test which produced the same result. 

Ok, this is what I wanted to check.

**Comment by DavePearce** [comment]
@lu-pinto Hey, so it feels like you made a [change to address this](https://github.com/Consensys/linea-besu/commit/139a0f151e89538797a7585b7082349a4e061c9a) and help us but then later have [reverted that change](https://github.com/Consensys/linea-besu/commit/98b6befc3c0ea619824cce0d74271693014a60c7).  Did I get that right?  What was the reason for the revert?  I'm assuming it broken something.

**Comment by lu-pinto** [comment]
@DavePearce @OlivierBBB closing this one as I think it's addressed now. Fell free to reopen if not
