### ISSUE TITLE
Does Besu spawn a `MessageFrame` for CALLs to precompiles ?

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#885]
In simple tests we see that Besu creates a `MessageFrame` for EOA calls but apparently not for precompile calls. Is that indeed the case and if so how to discover the `returnGas` i.e. the gas that is returned by the precompile to its caller ?

**Comment by lu-pinto** [comment]
Are you sure about that? I don't see any distinction between precompiles and others while executing `CALL`, see my answer [here](https://github.com/Consensys/linea-tracer/issues/869#issuecomment-2277974902).

Regarding the `returnGas` - do you mean the gas you pay on input data? I don't see any gas being taken while running the precompile code. Assuming that's the one, it only gets handed back in privacy based precompiled contracts from what I can see: [MessageCallProcessor.java#L161-L163](https://github.com/hyperledger/besu/blob/745d353027ff2998b22413ad6ca6bba7a2180699/evm/src/main/java/org/hyperledger/besu/evm/processor/MessageCallProcessor.java#L161-L163)

**Comment by letypequividelespoubelles** [comment]
answer is yes
