### ISSUE TITLE
Discrepency in line counting

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#889]
Issue arising thanks to @gusiri :

https://docs.google.com/spreadsheets/d/1Qtmt_KyUrkyB-GC1z5RuRYbm0T2_C8nVtqLT-BJO5IQ/edit?usp=sharing

Note: this is a conflation of a single block, so theoretically, the only difference should be for `WCP` module.

Small (ie < 10) could come from `spillings`.

**Comment by letypequividelespoubelles** [comment]
@gusiri Is it still relevant ?

**Comment by gusiri** [comment]
It turns out that a conflation generated by `replay()` has this issue. We don't have this issue with a conflation generated by `linea_generateConflatedTracesToFileV2`. `replay()` drops some transactions for various reasons, and these are being addressed by other issues.
