### ISSUE TITLE
`relBlock has invalid value (256)`

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#899]
## Ranges

Spotted by @gusiri 
```rust
2247091-2247391
```

**Comment by letypequividelespoubelles** [comment]
seems same issue as #877

**Comment by gusiri** [comment]
relBlock: relBlock is the relative block number, ranging from 1 to the total number of blocks

`full range: 2250131-2250478`: 
```

{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"relBlock has invalid value (256)"}}
real	2m34.476s
user	0m0.012s
sys	0m0.000s
```

When I divided the range into smaller ranges:

`range 1: 2250131-2250241`: Success
`range 2: 2250242-2250478`: Success

(256) means the max # of blocks. Only 255 blocks can be processed at once. 

-----

With 255 blocks : Success
With 256 blocks: Fail

`range: 2250131-2250385 (255 blocks)` 
```
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"0.5.0-beta","conflatedTracesFileName":"/data/besu/conflated/2250131-2250385.conflated.0.5.0-beta.lt"}}
real	2m15.539s
user	0m0.000s
sys	0m0.012s
```

`range: 2250131-2250386 (256 blocks)` 
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"relBlock has invalid value (256)"}}
```

**Comment by gusiri** [comment]
Should Besu or ZkTracer be configured to process a larger conflation?

**Comment by letypequividelespoubelles** [comment]
There is a prover limit of Max 200 tx in a batch iirc.

**Comment by gusiri** [comment]
It's a very old historical range when we had more than 255 tx in a batch. We might need to skip this range or temporarily use a larger `relBlock` for testing.

**Comment by FlorianHuc** [comment]
can be closed.
