### ISSUE TITLE
When does the caller's memory get updated relative to `traceContextReEntry` ?

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#913]
## Question

Consider a CALL operation which is
- **unexceptional**
- **unaborted** (in the sense of e.g. #869)

and which targets either a smart contract or a precompile. Taking for granted the conclusions of #869 in the case of precompiles and the expected control flow of smart contract calls, the CALL instruction will go through
- `traceContextEnter` (into callee context)
- `traceContextExit` (from callee context)
- `traceContextReEntry` (into caller context)

**Question.** When, relative to these hooks, is return data (partially) written to the caller's memory ? In particular does it happend
1. before `traceContextExit` ? [seems unlikely]
2. between `traceContextExit` and `traceContextReEntry` [seems plausible]
3. after `traceContextReEntry` [also plausible but seems less likely]

## Impact

This has a direct impact on all CALL's that emit return data @letypequividelespoubelles, in particular on MMU operations and when we should trigger them, i.e. whether they should take place in `resolveAtContextReEntry` or not. For instance this has an impact on whether we should trigger the `extractCallDataForXxx` MMU operation then or earlier. We may have to do it earlier if the memory update happens prior to `traceContextReEntry`.
- successful CALL's to smart contracts
- unsuccessful CALL's to smart contracts that terminate on a REVERT opcode
- successful CALL's to precompiles

**Comment by letypequividelespoubelles** [comment]
I'm not sure I get your point @OlivierBBB , all we need in the MmuCall object is the source and target ram before op. We don't need to give the updated RAM. So we just nes a snapshot of the memory at tracePreOpcode in my understanding.
For precompile's we give the return data in the exoBytes() field of the MmuCall. For callDataCopy and ExtCodeCopy, the MMU is able to take the right bytes from the rlpTxn / ROM.

**Comment by OlivierBBB** [comment]
I guess you are referring to 

<img width="705" alt="image" src="https://github.com/user-attachments/assets/b63dd392-84a2-4d90-bfb1-b38009554db9">

Good point, we do take the snapshot at creation of the `PrecompileSubsection`. Crisis averted 🙂.

**Follow up question:** do we do the same for general CALL's i.e. do we take a snapshot or equivalent so that we can correctly execute any follow up RETURN/REVERT ? Because we will need the unadulterated RAM of the caller at the point in time when the callee exits.

Or does the RETURN/REVERT instruction take care of this on its own ? That is likely what's going on.

**Comment by letypequividelespoubelles** [comment]
I don't know how was implemented the MmuCall for return and revert. I think you implemented it, or @lorenzogentile404 maybe ? 
But for sure we need a snapshot of source and target memory at tracePreOpcode of return

**Comment by lu-pinto** [comment]
> 2. between traceContextExit and traceContextReEntry [seems plausible]

That would be the time `traceContextExit` from child frame and `traceContextReEntry` on the parent. It happens when the `complete` handler is called upon notification that the child frame has finished executing [here](https://github.com/hyperledger/besu/blob/2158a6829676c75931ef5522f06332965fa6c4b6/evm/src/main/java/org/hyperledger/besu/evm/operation/AbstractCallOperation.java#L298-L303).
