### ISSUE TITLE
Add a mechanism to catch needed block hash in BlockCapturer

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#935]

**Comment by DavePearce** [comment]
@letypequividelespoubelles Do we have any block numbers we know invoke the `BLOCKHASH` bytecode?

**Comment by DavePearce** [comment]
Ok, some blocks which use the `BLOCKHASH` bytecode I have found:

* Block [8718330](https://lineascan.build/block/8718330)
* Block [8718090](https://lineascan.build/block/8718090) 

They seem to be few and far between.  They were found in scan of all blocks from `8718000` through to `8718375`.
