### ISSUE TITLE
fix the PostRollback Mechanism

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#939]

**Comment by OlivierBBB** [comment]
Could you explain what the fix is ? It's not clear from context that you commented stuff out for now.

**Comment by letypequividelespoubelles** [comment]
There was no fix. I just commented it out to have less java issues and help debuging, and open this issue to not forget to uncomment it.

The fix is now [here](https://github.com/Consensys/linea-tracer/pull/748/commits/ad009ee22b72dc69745d26d162765638a2ef2307) : we were exiting the context in the callStack BEFORE resolving the exit and rollback defers.
