### ISSUE TITLE
Incorrect `CHAINID` used in `ToyExecutionEnvironment`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#940]
_(this issue arises from investigations in #877)_

Whilst studying various replay tests, I have observed an unexpected difference from mainnet.  Specifically, the `CHAINID` is set incorrectly for execution in `ToyExecutionEnvironment` (and possibly other places perhaps).  This is despite considerable effort to set the `CHAINID` correctly.

Whilst observing the execution trace for the first transaction in block `6110045` I noticed this:

```
.. CHAINID  => 0x0000000000000000000000000000000000000000000000000000000000000539 
```

Here, `0x539` corresponds to the (default) chainID of 1337.  This is actually a BESU default.  The problem arises with the following line:

```
private final EVM evm = MainnetEVMs.london(EvmConfiguration.DEFAULT);
```

The problem here is that the `CHAINID` for the EVM (which is what will be reported by the `CHAINID` bytecode) is set by default, unless [explicitly passed in the constructor](https://github.com/hyperledger/besu/blob/main/evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java).

Suggested fix is:

1. Remove `evm` field altogether.
2. Instead, create an EVM within `getMainnetTransactionProcessor()` as follows:

```
private MainnetTransactionProcessor getMainnetTransactionProcessor() {
    EVM evm = MainnetEVMs.london(this.chainId, EvmConfiguration.DEFAULT);
    ...
``` 

This then correctly sets the `CHAINID` as reported by the corresponding bytecode.  I can't really judge whether this is a significant issue or not.

@letypequividelespoubelles FYI

**Comment by letypequividelespoubelles** [comment]
How come it doesn't break the ChainId constraint in BLOCK_DATA ?

edit: my bad, we don't impose the value of ChainID in BLOCK_DATA, but only its smallness, and matching the value we have in RLP_TXN : https://github.com/Consensys/linea-specification-internal/issues/498

**Comment by DavePearce** [comment]
> How come it doesn't break the ChainId constraint in BLOCK_DATA ?

Well, I don't specifically know.  But I can say that the chain ID is set correctly in other places.  In particular, the `ZkTracer` has a field `chainID` which was set correctly.  Its just the `EVM` instance which has the incorrect chainID.  So I guess that would be the reason.

The interesting thing is that some addresses used for `SSTORE` are hashed using `CHAINID` and, hence, fixing this changes some storage locations (to correct ones where previously they were mismatched).  However, this still does not resolve all issues.
