### ISSUE TITLE
feat: advanced testing framework

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/besu-sequencer-plugins#955]
Notes from @OlivierBBB: https://hackmd.io/@olivierbbb/SkOB9AWsC

The purpose of this issue is summarising possible approach to build an advanced testing framework.

First of all, we should check if there is already something existing and ready to use in Java.

If not:

**Approach A**

The testing library should allow:

- **Code composition**: it should be possible to create Solidity smart contract by composing Solidity **functions** or Solidity **snippets**. If necessary (if not compiled already), the compilation of the obtained smart contract should be triggered by the `linea-tracer` itself. 

Note: Currently, in order to do not create too many smart contracts to test different slightly different cases, we create larger than necessary smart contracts (e.g., in the case of `SELFDESTRUCT`) and we interact with them in different ways. Such modularity, would allow a more flexible way to define smart contracts for testing that contain only what we need for the specific test case.

- **Behaviour definition**: a test case can be identified by indicating an entry point in a tree of smart contracts via a call to a function (or the constructor). A basic graphical representation (using ASCII) of the behaviour we want to test may be helpful and could be generated. 

- **Assembly, Yul, Bytecode injection**:  in order to by-pass Solidity compiler restrictions and test more in depth our software, we may want to inject in the Solidity smart contracts directly assembly, Yul or Bytecode. Understanding which one is the best approach has to be researched.

Note: mapping Java on Solidity instead of Bytecode directly may make the process quicker and **is not a limitation due to the observation above**. Mapping Java directly on Bytecode may lead to face the complexity of creating a Solidity-like language in Java, that is unnecessary;

Feel free to add other ideas below.

**Comment by OlivierBBB** [comment]
## Desiderata

A complex contract **B** that can CREATE2 with complex **initC** potentially leading to the deployment of complex contract **C** with complex behaviour, too. They should be able to call each other (in all possible combinations) and do other complex stuff.

### Contract B

A contract **B** which can:
- CALL itself (with `value` / `gas` as parameters that can be set)
- STATICCALL itself (with `gas` parameter that can be set)
- CALL / STATICCALL **C** (will be defined below)
- REVERT on demand
- provoke an `outOfGasException` on demand (e.g. some big SHA3)
- SELFDESTRUCT on demand
- run a pametrized CREATE2 with fixed init code (parameters: `value`)

### Initialization code initC

Some init code **initC** that can:
- CALL **B** on demand (e.g. to attempt asking **B** to re-deploy with **initC**)
- SSTORE during deployment and on demand
- SELFDESTRUCT during deployment and on demand
- REVERT during deployment on demand
- EXTCODEHASH/COPY/SIZE from either **B** or itself (via ADDRESS)
- CODECOPY from itself

### Deployed contract C

**initC** should, if it leads to a deployment, always deploy the same code (e.g. obtained by an EXTCODESIZE / EXTCODECOPY / RETURN combo) or to empty deployment code or to a failed deployment. When it deploys nontrivially the resulting account **C** should be able to
- SSTORE, in particular at storage keys that may have been touched during deployment,
- SELFDESTRUCT on demand
- REVERT on demand
- CALL **B** on demand

### Complex example run

Reading order:
- bottom to top
- at a node, read in clock-wise order

![20240825_235035](https://github.com/user-attachments/assets/a1338e23-f535-452f-a00b-991ba423842e)

Slightly more readable picture (of a slightly more complex scenario)

![20240826_001632](https://github.com/user-attachments/assets/a8d0c0df-6ca6-435c-8f9f-1c257e700176)

**Comment by julien-marchand** [comment]
Closing, please reopen an issue if necessary.

**Comment by OlivierBBB** [comment]
For scenarios such as the above to be possible, where the execution of some given initialization code `initC` leads to vastly different executions, one needs to be able to **pilot** the execution of the init code `initC`. Indeed `initC` attempts to
- to deploy some `deployedCode1` to be called later
- alternatively, to deploy some `deployedCode2` to be called later
- ...
- `CALL` back to `B` to trigger its own re-deployment ...

We can't pilot `initC`'s execution through `callData` --- deployments have empty call data. One can however pilot `initC`'s execution by means of external smart contracts. For instance one can have a `methodPilot` contract with two methods
```java
public void setMethods(String[] methodNames) { ... }
public String[] getMethods() { ... }
```
(using java like syntax.) These methods can be called ahead of time by `B` (via `setMethods`) and `initC` may have a hardcoded `CALL` to the `methodPilot` smart contract (to `getMethods`) followed by a for loop over the return data (which is an array of method names) and a loop for every method name over all of `initC`'s valid method names (identifiers) and a `JUMPI` on match to the relevant method in `initC`.

You can also have a smart contract called `deploymentCodeSelector` with a method
```java
public void setCodeAddress(Address address) { ... }
public Address getCodeAddress() { ... }
```
with a method in `initC` that does a call to `deploymentCodeSelector` with the `getCodeAddress` method and which `SSTORE`'s it at `foreignCodeAddressKey` followed up by
```
PUSH32 foreignCodeAddressKey
SLOAD
EXTCODESIZE
PUSH1 0
PUSH1 0
PUSH32 foreignCodeAddress
SLOAD
EXTCODECOPY
PUSH32 foreignCodeAddress
SLOAD
EXTCODESIZE
PUSH1 0
RETURN
```
(something to that effect) which fully copies the `foreignCodeAddress`' code to RAM and `RETURN`'s it as deployment code etc ... Again the idea would be to set the `deploymentCodeSelector`'s pointer before the relevant `CREATE2` gets executed etc ...
