### ISSUE TITLE
Incorrect implementation of `ToyWorld.commit()`

### ISSUE THREAD

**Issue by DavePearce** [Consensys/besu-sequencer-plugins#964]
By comparing execution using `ToyWorld` vs `org.hyperledger.besu.evm.fluent.SimpleWorld`, we can see a problem with `ToyWorld.commit()`.  Currently, it is:

```
    if (parent != null) {
      parent.addressAccountMap.putAll(addressAccountMap);
    }
```
However, with this implementation, [Block 6110040](https://lineascan.build/tx/0xe3e410ddcd6286a9e67ea75f82c654c81c49ec5d2696b7059885af7bf5b2316c#internal) tx `0xe3e410ddcd6286a9e` incorrectly reverts.  However, using the implementation from `SimpleWorld` and it succeeds:

```
    addressAccountMap.forEach(
      (address, account) -> {
        if (!account.updateParent()) {
          parent.addressAccountMap.put(address, account);
        }
      });
```

**NOTE:** I would personally suggest using `SimpleWorld` instead of `ToyWorld` for the replay tests at least.  Ideally, we could drop `ToyWorld` altogether --- though I am unsure whether that is possible at this stage.  The reason being simply less code to maintain.

@letypequividelespoubelles @powerslider FYI --- next one identified.  Will make the PR now.

**Comment by OlivierBBB** [comment]
@gauravahuja @powerslider  What is your opinion on the `ToyWorld` vs `SimpleWorld` ? How would that relate to the `ToyWorld` update ?

**Comment by gauravahuja** [comment]
From the perspective of the [ToyExecutionEnvironmentV2](https://github.com/Consensys/linea-tracer/blob/arith-dev/testing/src/main/java/net/consensys/linea/testing/ToyExecutionEnvironmentV2.java), I just need a list of accounts.

ToyExecutionEnvironmentV2 builds the [GeneralStateTestCaseEipSpec](https://github.com/gauravahuja/besu/blob/main/ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/GeneralStateTestCaseEipSpec.java) and uses this spec object to run the test similar to how reference tests execute.

GeneralStateTestCaseEipSpec requires a [ReferenceTestWorldState](https://github.com/gauravahuja/besu/blob/main/ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestWorldState.java) which can be created with a list of accounts and evm configuration. Thus I can use either ToyWorld, SimpleWorld or just a list of accounts to build the test spec.
