### ISSUE TITLE
nonce of sender not updated in the ToyWorld 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#968]
When we run a replayTest, the nonce is not updated, and so if a sender sends more than one tx, only the first tx is accepted : 

![image](https://github.com/user-attachments/assets/0643760c-5db0-4822-ae7c-51464540a4d3)

**Comment by DavePearce** [comment]
Did you try applying the fix from #964?  That is related to commiting of accounts and is merged into `arith-dev` now.

**Comment by DavePearce** [comment]
Also, the first `tx` in that block reverts.  Which block number is this?

**Comment by letypequividelespoubelles** [comment]
@DavePearce @gauravahuja  as we don't use ToyWorld anymore I guess we can close this ?
